# Generated by Django 4.0.5 on 2022-06-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_katagorimodel_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KatagoriModel',
            new_name='KategoriModel',
        ),
    ]
