# Generated by Django 4.0.5 on 2022-06-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_yorummodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazilarmodel',
            old_name='duzenlenme_tarihi',
            new_name='guncelleme_tarihi',
        ),
        migrations.RenameField(
            model_name='yorummodel',
            old_name='guncelleme_tarhi',
            new_name='guncelleme_tarihi',
        ),
    ]
